name: PHP Stan

on:
  push:
    branches:
      - "master"
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - reopened

jobs:
  test:
    # Setup ubuntu latest
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    name: "PHPStan Badaso Post Module"

    steps:
      - uses: actions/checkout@master

      # Badaso PostModule Test PHPStan
      - name: Badaso PostModule test PHPStan
        run: ./vendor/bin/phpstan analyse -c phpstan.neon.dist
